import json
import asyncio
from datetime import datetime
from typing import Set, Dict, Any, Optional
from fastapi import WebSocket, WebSocketDisconnect
from app.normalizer.schema import ShadowEvent

class WebSocketEventBus:
    def __init__(self):
        self.active_connections: Set[WebSocket] = set()
        self.lock = asyncio.Lock()

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        async with self.lock:
            self.active_connections.add(websocket)

    async def disconnect(self, websocket: WebSocket):
        async with self.lock:
            self.active_connections.discard(websocket)

    async def broadcast(self, message_type: str, data: Any):
        """Broadcast typed JSON payload to all connected Web Console clients."""
        payload = {
            "type": message_type,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "data": data
        }
        text_data = json.dumps(payload, default=str)
        
        async with self.lock:
            disconnected = set()
            for connection in self.active_connections:
                try:
                    await connection.send_text(text_data)
                except Exception:
                    disconnected.add(connection)
            for dead in disconnected:
                self.active_connections.discard(dead)

    async def publish_event(self, event: ShadowEvent):
        """Broadcast newly normalized 29-field event to live timeline."""
        await self.broadcast("NEW_EVENT", event.model_dump())

    async def publish_detection(self, detection: Dict[str, Any]):
        """Broadcast alert generated by detection engine."""
        await self.broadcast("DETECTION_TRIGGERED", detection)

    async def publish_asset_diff(self, asset_diff: Dict[str, Any]):
        """Broadcast continuous discovery change (discovered, state change, IP change)."""
        await self.broadcast("ASSET_DIFF", asset_diff)

    async def publish_purple_update(self, purple_data: Dict[str, Any]):
        """Broadcast live exercise progression, validation milestone, or score."""
        await self.broadcast("PURPLE_UPDATE", purple_data)

    async def publish_health(self, health_data: Dict[str, Any]):
        """Broadcast 4-state operational health update."""
        await self.broadcast("HEALTH_UPDATE", health_data)

event_bus = WebSocketEventBus()
