from fastapi import APIRouter, Depends, Query
from datetime import datetime
from typing import Dict, Any, List, Optional
from sqlalchemy import select, func
from app.database import get_db, AsyncSession, DetectionModel
from app.engine.mitre_correlator import mitre_correlator

router = APIRouter(prefix="/detections", tags=["Detections & ATT&CK Coverage"])

@router.get("/")
async def list_detections(
    limit: int = Query(default=50, le=200),
    severity: Optional[str] = None,
    db: AsyncSession = Depends(get_db)
) -> Dict[str, Any]:
    """Source-of-truth alert detections generated by Sigma rules."""
    query = select(DetectionModel).order_by(DetectionModel.triggered_at.desc()).limit(limit)
    if severity:
        query = query.where(DetectionModel.severity == severity)
        
    res = await db.execute(query)
    detections = res.scalars().all()

    # Calculate severity counts
    crit = sum(1 for d in detections if d.severity == "critical")
    high = sum(1 for d in detections if d.severity == "high")
    med = sum(1 for d in detections if d.severity == "medium")

    return {
        "metric": "Active Detections",
        "value": len(detections),
        "critical_count": crit,
        "high_count": high,
        "medium_count": med,
        "detections": [
            {
                "detection_id": d.detection_id,
                "title": d.title,
                "rule_name": d.rule_name,
                "severity": d.severity,
                "mitre_tactic": d.mitre_tactic,
                "mitre_technique": d.mitre_technique,
                "triggered_at": d.triggered_at.isoformat() + "Z" if d.triggered_at else None,
                "event_id": d.event_id,
                "hostname": d.hostname,
                "status": d.status,
                "risk_score_delta": d.risk_score_delta
            }
            for d in detections
        ],
        "source": "detection_engine",
        "last_updated": datetime.utcnow().isoformat() + "Z",
        "status": "live" if len(detections) > 0 else "no_telemetry",
        "confidence": 1.0
    }

@router.get("/mitre-matrix")
async def get_mitre_matrix() -> Dict[str, Any]:
    """Evidence-backed MITRE ATT&CK coverage matrix."""
    return await mitre_correlator.get_coverage_matrix()
